name: App
attributes:
- name: id
  type: string
- name: obj_type
  type: string
- name: name
  type: string
- name: description
  type: string
- name: path
  type: string
- name: version
  type: string
- name: role_required
  type: bool