module: github.com/GPA-Gruppo-Progetti-Avanzati-SRL/opem-store
package: github.com/GPA-Gruppo-Progetti-Avanzati-SRL/opem-store/store/cms
imports:
  - ../commons/schema.yml
entities:
- file-name: ./file.yml
  document: true
  package: github.com/GPA-Gruppo-Progetti-Avanzati-SRL/opem-store/store/cms/file
- file-name: ./ent-ref-struct.yml
  package: github.com/GPA-Gruppo-Progetti-Avanzati-SRL/opem-store/store/cms/file

# @tpm-schematics:start-region("bottom-file-section")
# @tpm-schematics:end-region("bottom-file-section")
