name: Prodotto
attributes:
- name: oId
  type: object-id
  options: with-filter
  tags:
    - name: json
      value: _id,omitempty
    - name: bson
      value: _id,omitempty
    - name: yaml
      value: _id,omitempty
- name: domain
  type: string
  options: with-filter
- name: site
  type: string
  options: with-filter
- name: _bid
  type: string
  options: with-filter
- name: _et
  type: string
  options: with-filter
- name: name
  type: string
- name: primary_funct
  type: string
- name: code
  type: string
- name: expiration_at
  type: string
  options: with-filter
- name: sys_info
  struct-ref:
    name: SysInfo
  type: struct
