module: github.com/GPA-Gruppo-Progetti-Avanzati-SRL/opem-store
package: github.com/GPA-Gruppo-Progetti-Avanzati-SRL/opem-store/store/prodotto
imports:
  - ../commons/schema.yml
entities:
- file-name: ./prodotto.yml
  document: true
  package: github.com/GPA-Gruppo-Progetti-Avanzati-SRL/opem-store/store/prodotto/prodotto
- file-name: ./app-definition.yml
  package: github.com/GPA-Gruppo-Progetti-Avanzati-SRL/opem-store/store/prodotto/prodotto
- file-name: ./app-number-definition.yml
  package: github.com/GPA-Gruppo-Progetti-Avanzati-SRL/opem-store/store/prodotto/prodotto
- file-name: ./host_product.yml
  package: github.com/GPA-Gruppo-Progetti-Avanzati-SRL/opem-store/store/prodotto/prodotto

# @tpm-schematics:start-region("bottom-file-section")
# @tpm-schematics:end-region("bottom-file-section")
