module: github.com/GPA-Gruppo-Progetti-Avanzati-SRL/opem-store
package: github.com/GPA-Gruppo-Progetti-Avanzati-SRL/opem-store/store/commons
entities:
- file-name: ./sys-info.yml
- file-name: ./user-role.yml
- file-name: ./app.yml
- file-name: ./file-variant.yml
- file-name: ./file-reference.yml
- file-name: ./address.yml
- file-name: ./bid-text-pair.yml
- file-name: ./value-text-pair.yml
- file-name: ./value-range.yml
- file-name: ./address.yml
- file-name: ./note.yml
- file-name: ./event.yml
# @tpm-schematics:start-region("bottom-file-section")
# @tpm-schematics:end-region("bottom-file-section")
